dist: trusty
language: python
python:
	- 2.7
	- 3.6.1

install:
	- pip install -r requirements.txt
	- pip install -r requirements_test.txt

script:
	- flake8 tensorrec
	- nosetests --with-timer

notifications:
	email: false